### ISSUE TITLE
The 0 byte message should not be discarded, we need it for the MPI latency metric

### ISSUE THREAD

**Issue by ohm314** [tristan0x/hpcbench#113]
https://github.com/tristan0x/hpcbench/blob/5cc1f17a80e956492bdc408c2ce313b7b3a18d55/hpcbench/benchmark/imb.py#L90:L93

**Comment by tristan0x** [comment]
I think @timocafe wanted me to do it that way.

**Comment by timocafe** [comment]
Yes let say it like this, every "message" are encapsulate into a shell (network communication). A 0 byte message is the latency of this shell more over I am quite sure the default buffer is [8-16] byte (a cache line).

So for the beginning let keeps this "0 byte" message and we should compare it at 1 byte message. 
From my experience number should one the same.

**Comment by ohm314** [comment]
so, as it turns out, on some implementations and some systems using the 0 byte message is a bad idea. the latencies reported there are way too small. Some implementations take a shortcut in this case. at the same time, when i run IMB-MPI1 with --logmsg 21:22 to restrict to only large messages, then I can't get any reasonable latency with this strategy because I use for the latency the 2**21 large message.
The solution here is to use IMB-MPI1 feature to pass a file with message sizes, which could be generated from configurations in the yaml file.

**Comment by ohm314** [comment]
we moved on to using mostly OSU. IMB remains in the code for legacy for now.
