### ISSUE TITLE
don't copy hpl exectuable into the hpcbench report directory

### ISSUE THREAD

**Issue by ohm314** [tristan0x/hpcbench#129]
this is causing huge numbers of binaries to be duplicated. Final report directories are several GB big for even a moderately sized cluster.
@tristan0x : Is there any specific reason the executables were being copied in the first place?

**Comment by tristan0x** [comment]
I guess hpl executable requires the Dat file to be located on the same dir.
You can implement post_execution hook in hpl.py to remove the executable.

**Comment by ohm314** [comment]
it only needs to be in the cwd - so no need to copy the binary at all :)
