### ISSUE TITLE
allow running benchmarks with slurm constraints rather than explicit node lists

### ISSUE THREAD

**Issue by ohm314** [tristan0x/hpcbench#137]
For now we use `--nodelist` with srun to define which nodes hpcbench should request with srun to run on. This is not compatible with a production system, because we will often find the specific nodes already allocated. Much more effective and useful for most benchmarks is a mode in which we define tags with constraints that should be fulfilled.
Specific example:

A simple osu sbatch script would look like this:

```bash
#!/bin/bash -l
#SBATCH -t 08:00:00 
#SBATCH -p prod

module purge
module load nix/osu-mpi-bench

echo "SLURM_NTASKS: $SLURM_NTASKS" 
echo "SLURM_NTASKS_PER_NODE: $SLURM_NTASKS_PER_NODE"
echo "SLURM_NODELIST: $SLURM_NODELIST"

srun --account=proj16 --mpi=pmi2 osu_allgatherv -m 32:1024 -x 200 -i 100
```

calling this sbatch script on 6 UC1 nodes and 6 UC2 nodes can be done as follows:

```bash
sbatch --account=proj16 --partition=prod --exclusive \
  -C "uc1*6|uc2*6" -N 12 --ntasks-per-node=36 ./osu_coll_mva.sbatch
```

Note the `-C` or `--constraint` argument.

**Comment by tristan0x** [comment]
#138 provides implementation of the _easy solution_

**Comment by tristan0x** [comment]
I am starting the implementation of the new tag _constraint_ type.

The campaign.yaml documentation has to be updated according to:
* new slurm executor / new ben-sh options
* sbatch Jinja templates
* constraint tag

@ohm314 I suggest you take care of the slurm executor, I take the rest. Would that be OK?

**Comment by ohm314** [comment]
Sounds good. Updating documentation and cleaning up code was anyway my next
step.

**Comment by ohm314** [comment]
constraints can now be defined inside the network section
