### ISSUE TITLE
Keep best of several runs

### ISSUE THREAD

**Issue by tristan0x** [tristan0x/hpcbench#16]
## Rationale

Because benchmarking should always be executed on warm caches, we
may need to execute a benchmark several times before taking its metrics
into consideration.

## Introduction

The following technical specification is an initial proposal
describing the different ways to specify such behaviour.

## Use case

Consider the following incomplete `HelloWorld` benchmark class:

```python
class HelloWorld(hpcbench.api.Benchmark):
  @property
  def execution_matrix(self):
      for thread in [1, 4, 8]:
          return dict(
              command=["hello_world", "-t", str(thread)],
              metas=dict(
                  thead=thread
              )
          )
```
The `HelloWorld` benchmark execution phase will launch 3 commands. For every command, we would like to describe:

1. the number of times the command must be executed
1. which runs must be retained

Proposals below introduce a new `attempts` key in the dictionary structure of the `execution_matrix` class property.

## Execution count

There can be several ways to specify how many times a command has to be run:

* fixed
* dynamic

### fixed number of times

   ```python
   attempts=dict(
     count=dict(
       fixed=4,
     )
   )
   ```
### dynamic number of times

We may want to execute a command as long as a metric's value converge to a certain value.

* by specifying a fixed `epsilon` value, execution will stop at `nth` run if: ![\left | M(n) - M(n -1) \right | < \epsilon](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cleft%20%7C%20M%28n%29%20-%20M%28n%20-1%29%20%5Cright%20%7C%20%3C%20%5Cepsilon)

   ```python
   attempts=dict(
     count=dict(
       convergence=dict(
         metric="bandwidth",
         epsilon=0.3,
       )
     )
   )
   ```

* by specifying a `P` percent value, execution will stop at `nth` run if: ![\left | M(n) - M(n -1) \right | < \left M(n - 1) \right \times P / 100](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cleft%20%7C%20M%28n%29%20-%20M%28n%20-1%29%20%5Cright%20%7C%20%3C%20%5Cleft%20%7C%20M%28n%20-%201%29%20%5Cright%20%7C%20%5Ctimes%20P%20/%20100)

   ```python
   attempts=dict(
     count=dict(
       convergence=dict(
         metric="bandwidth",
         percent=5,
       )
     )
   )
   ```

## Run selection

Now that we are able to execute a serie of runs for a particular command, we can define a way to specify which one of them is selected.

HPCBench will always pick the latest, and there is nothing particular to
configure. This behaviour perfectly suits the use cases described above.

Nevertheless, the user is able to sort the serie of runs so that HPCBench
picks the proper one. API mimics the Python `sorted` method signature:

   ```python
   sorted(iterable, cmp=None, key=None, reverse=False)
   ```

   * *cmp*: a callable taking 2 runs in parameter, returning either -1, 0 or 1
   * *key*: callable taking a run in parameter, and returning the sorting key
   * reverse: a boolean to reverse the sort order

   For instance:

   ```python
   attempts=dict(
     count=dict(
       fixed=3
     ),
     sort=dict(
       cmp=<callable>,
       reverse=True, 
     ),
   )
   ```

**Comment by fouriaux** [comment]
I think depending of the purpose of hpcbench:
What I mean is: if we see hpcbench as a benchmark driver, we expect the benchmarks to produce relevant figures: it is the responsibility of benchmarks to specify what does it produce and to guaranty its relevance ( avg, max, min) etc... 
In this case, HPCbench responsibility is to distributes the launches on nodes with correct configurations and gather produced figures.
In this viewpoint, I think it simplifies and avoid confusion of getting a lot of disparity between user scripts.

What is your opinion ? May be I overlook some cases that makes indeed this feature mandatory...

**Comment by tristan0x** [comment]
Thank you @fouriaux for you feedback.
Yes, indeed this is not required for _stream_, and I agree with you that benchmark utilities used by HPCBench should always return relevant results. Unfortunately this is not always the case and I would like to prevent patching those utilities directly so that they meet such expectation.

For instance @adevress and I tried [mdtest](https://github.com/LLNL/mdtest) on GPFS and results are quite different when you execute the utility more than once.

We could think of an utility between HPCBench and the benchmark software itself that would take care of running the test several times, but it would need to extract metrics like HPCBench is doing.

@adevress what do you think of this proposal?

**Comment by fouriaux** [comment]
My sarcastic question of the day: 
Does a benchmark is more relevant as a benchmark or as a random number generator if it provides very different results between runs :-D 

More seriously: my understanding is to properly benchmark GPFS best case we will need to run completely exclusively on the machine, in the same way that we requires exclusivity of a Node when performing stream or computational benchmarks...

**Comment by tristan0x** [comment]
I am afraid that running exclusively on a machine is not enough because benchmark metrics are quite different when GPFS caches are warmed. So the question here is not whether it is required to be able to run a benchmark more than once or not, because it definitely does.
What I would like your opinion about is more on how the proposal handles this requirement.

**Comment by fouriaux** [comment]
ok, I understand :-)
I think the spec is quite consistent, I really like the run selection. 
here are my 2 cents on Convergence: 
-- I will make a max number of run mandatory in convergence dictionary, just to avoid huge amount of runs by mistake if no convergence at epsilon is found.

**Comment by tristan0x** [comment]
Thank you for you feedback @fouriaux 
You are right, there should be some kind of security mechanism to prevent running the benchmark forever. I will implement what you suggest.
