### ISSUE TITLE
Insufficient permissions in generated shell-script

### ISSUE THREAD

**Issue by tristan0x** [tristan0x/hpcbench#211]
https://github.com/tristan0x/hpcbench/blob/5241af511d6e20c103ff54efc193a650f40fff94/hpcbench/driver.py#L1012

`tempsfile.mkstemp` [documentation](https://docs.python.org/2/library/tempfile.html#tempfile.mktemp) says only the owner can access the file.

Other users should at least be able to read it.

**Comment by ohm314** [comment]
This is done
